import React, { useState } from 'react';
import { Icons } from '../icons';

export const jobApplicationListings = [
  {
    title: 'Captain - A320 family',
    company: 'Etihad',
    aircraft: 'A320 family',
    location: 'United Arab Emirates (UAE) | Abu Dhabi',
    role: 'Captain',
    url: 'https://pilotsglobal.com/job/A320-family-captain-etihad-AE-81Oyt9ulnn',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '5500',
    license: 'ATP / ATPL',
    visaSponsorship: 'Yes',
    picTime: '2500',
    picInTypeTime: '1500',
    typeRating: 'Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '4',
    compensation: 'Up to AED 637,304 (USD 171,589) per year'
  },
  {
    title: 'Captain - Citation III / VI / VII',
    company: 'SXM Airways',
    aircraft: 'Citation III / VI / VII',
    location: 'Sint Maarten | Philipsburg',
    role: 'Captain',
    url: 'https://pilotsglobal.com/job/Citation-III-VI-VII-captain-sxm_airways-SX-bfwTt3048n',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '3000',
    license: 'ATP / ATPL',
    visaSponsorship: 'Yes',
    picTime: '1500',
    picInTypeTime: '50',
    typeRating: 'Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '4',
    compensation: 'Competitive package with benefits'
  },
  {
    title: 'First Officer - A320 family',
    company: 'Etihad',
    aircraft: 'A320 family',
    location: 'United Arab Emirates (UAE) | Abu Dhabi',
    role: 'First Officer',
    url: 'https://pilotsglobal.com/job/A320-family-first-officer-etihad-AE-Cm8ut9ulzu',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '2000',
    license: 'ATP-qualified / fATPL / IATRA,IR,ME',
    visaSponsorship: 'Yes',
    picTime: '',
    picInTypeTime: '',
    typeRating: 'Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '4',
    compensation: 'Up to AED 513,732 (USD 138,318) per year'
  },
  {
    title: 'Captain - A320 family',
    company: 'Air Astana',
    aircraft: 'A320 family',
    location: 'Kazakhstan | Almaty',
    role: 'Captain',
    url: 'https://pilotsglobal.com/job/A320-family-captain-air_astana-KZ-bd8b243d49',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '4500',
    license: 'ATP / ATPL',
    visaSponsorship: 'Yes',
    picTime: '1000',
    picInTypeTime: '500',
    typeRating: 'Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '4',
    compensation: 'Competitive salary with housing allowance'
  },
  {
    title: 'Captain - Challenger CL-30',
    company: 'Executive Jet Management (EJM)',
    aircraft: 'Challenger CL-30',
    location: 'United States | Cincinnati',
    role: 'Captain',
    url: 'https://pilotsglobal.com/job/Challenger-CL-30-captain-executive_jet_management_ejm-US-2aaca6a488',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '3500',
    license: 'ATP / ATPL',
    visaSponsorship: 'No',
    picTime: '2000',
    picInTypeTime: '',
    typeRating: 'Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '',
    compensation: 'Competitive pay with comprehensive benefits'
  },
  {
    title: 'Pilot Cadet - Various Aircraft',
    company: 'Envoy Air',
    aircraft: 'Various Aircraft',
    location: 'United States | Home-Based',
    role: 'Pilot Cadet',
    url: 'https://pilotsglobal.com/job/Various-Aircraft-pilot-cadet-envoy_air-US-0f69556e44',
    posted: '2025-03-19',
    status: 'Accepting Apps',
    applicationUrl: '',
    flightTime: '40',
    license: 'CPL',
    visaSponsorship: 'No',
    picTime: '',
    picInTypeTime: '',
    typeRating: 'Not Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '',
    compensation: 'Financial assistance and guaranteed path to First Officer'
  },
  {
    title: 'Captain - G650',
    company: 'Jet Aviation',
    aircraft: 'G650',
    location: 'United States | Van Nuys',
    role: 'Captain',
    url: 'https://pilotsglobal.com/job/G650-captain-jet_aviation-US-3bcda382f3',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '3500',
    license: 'ATP / ATPL',
    visaSponsorship: 'No',
    picTime: '1500',
    picInTypeTime: '',
    typeRating: 'Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '',
    compensation: 'Competitive benefit package with 401(k) and insurance'
  },
  {
    title: 'Corporate Pilot - Falcon 2000',
    company: 'Davinci Jets',
    aircraft: 'Falcon 2000',
    location: 'United States | Concord (NC)',
    role: 'Corporate Pilot',
    url: 'https://pilotsglobal.com/job/Falcon-2000-corporate-pilot-davinci_jets-US-tJNhtbbrbp',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: 'ATP / ATPL',
    visaSponsorship: 'No',
    picTime: '',
    picInTypeTime: '',
    typeRating: 'Not Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '',
    compensation: 'Performance-based compensation package'
  },
  {
    title: 'Second in Command - Learjet LR-45',
    company: 'Jett Aircraft',
    aircraft: 'Learjet LR-45',
    location: 'United States | Fayetteville (AR)',
    role: 'Second in Command',
    url: 'https://pilotsglobal.com/job/Learjet-LR-45-second-in-command-jett_aircraft-US-keyQsa04e5',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '500',
    license: 'ATP / ATPL',
    visaSponsorship: 'No',
    picTime: '',
    picInTypeTime: '',
    typeRating: 'Not Required',
    medicalClass: 'Class 2',
    icaoElpLevel: '',
    compensation: 'Base Salary: $39,550.00 + Total Yearly Salary: $79,000.00'
  },
  {
    title: 'Captain - ERJ family EMB-145',
    company: 'Hendrick Motorsports',
    aircraft: 'ERJ family EMB-145',
    location: 'United States | Concord',
    role: 'Captain',
    url: 'https://pilotsglobal.com/job/ERJ-family-EMB-145-captain-hendrick_motorsports-US-BG1ys74dgv',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '3000',
    license: 'ATP / ATPL',
    visaSponsorship: 'No',
    picTime: '1500',
    picInTypeTime: '',
    typeRating: 'Not Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '',
    compensation: 'Competitive salary with comprehensive benefits'
  },
  {
    title: 'Corporate Pilot - Global Express',
    company: 'PrivateFlite Aviation',
    aircraft: 'Global Express',
    location: 'United States | Louisville',
    role: 'Corporate Pilot',
    url: 'https://pilotsglobal.com/job/Global-Express-corporate-pilot-privateflite_aviation-US-SsIvtb0vh2',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '2000',
    license: 'ATP / ATPL',
    visaSponsorship: 'No',
    picTime: '',
    picInTypeTime: '',
    typeRating: 'Not Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '',
    compensation: 'Salary: $130,000-$175,000 with signing bonus'
  },
  {
    title: 'Check Airman - ERJ family EMB-145',
    company: 'Contour Aviation',
    aircraft: 'ERJ family EMB-145',
    location: 'United States | Houston',
    role: 'Check Airman',
    url: 'https://pilotsglobal.com/job/ERJ-family-EMB-145-check-airman-contour_aviation-US-cmEdtc2id1',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: 'ATP / ATPL',
    visaSponsorship: 'No',
    picTime: '',
    picInTypeTime: '',
    typeRating: 'Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '',
    compensation: 'Competitive salary with 401(k) match up to 6%'
  },
  {
    title: 'First Officer - CRJ Series',
    company: 'GoJet Airlines',
    aircraft: 'CRJ Series',
    location: 'United States | Newark',
    role: 'First Officer',
    url: 'https://pilotsglobal.com/job/CRJ-Series-first-officer-gojet_airlines-US-45a2f4d32c',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '750',
    license: 'ATP-qualified / fATPL / IATRA',
    visaSponsorship: 'No',
    picTime: '',
    picInTypeTime: '',
    typeRating: 'Not Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '',
    compensation: 'Starting pay: $92.72 per flight hour + Per Diem: $2.05'
  },
  {
    title: 'Pilot in Command - Various Business Jet',
    company: 'Wing Aviation',
    aircraft: 'Various Business Jet',
    location: 'United States | Houston',
    role: 'Pilot in Command',
    url: 'https://pilotsglobal.com/job/Various-Business-Jet-pilot-in-command-wing_aviation-US-PAfOsgp2fs',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '3500',
    license: 'ATP / ATPL',
    visaSponsorship: 'No',
    picTime: '1500',
    picInTypeTime: '250',
    typeRating: 'Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '',
    compensation: 'Competitive compensation package'
  },
  {
    title: 'Captain - GVII / G500-G650',
    company: 'Solairus Aviation',
    aircraft: 'GVII / G500-G650',
    location: 'United States | Teterboro',
    role: 'Captain',
    url: 'https://pilotsglobal.com/job/GVII-G500-G650-captain-solairus_aviation-US-g713t0ms4g',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '3000',
    license: 'ATP / ATPL',
    visaSponsorship: 'No',
    picTime: '1500',
    picInTypeTime: '',
    typeRating: 'Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '',
    compensation: 'Competitive salary with comprehensive benefits'
  },
  {
    title: 'Captain - Citation I / I/SP',
    company: 'Jet Air',
    aircraft: 'Citation I / I/SP',
    location: 'United States | Galesburg',
    role: 'Captain',
    url: 'https://pilotsglobal.com/job/Citation-I-I-SP-captain-jet_air-US-nYjSsm5cni',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '3000',
    license: 'ATP / ATPL',
    visaSponsorship: 'No',
    picTime: '1500',
    picInTypeTime: '',
    typeRating: 'Not Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '',
    compensation: 'Health / Life Insurance, 401(k), Profit Sharing'
  },
  {
    title: 'Director of Flight Operations - King Air',
    company: 'Freeman Jet Center',
    aircraft: 'King Air',
    location: 'United States | Abilene',
    role: 'Director of Flight Operations',
    url: 'https://pilotsglobal.com/job/King-Air-director-of-flight-operations-freeman_jet_center-US-CPV0t04wn8',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '3000',
    license: 'ATP / ATPL',
    visaSponsorship: 'No',
    picTime: '1200',
    picInTypeTime: '',
    typeRating: 'Not Required',
    medicalClass: 'Class 2',
    icaoElpLevel: '',
    compensation: 'Comprehensive package with 401(k) and PTO'
  },
  {
    title: 'Pilot in Command - Various Business Jet',
    company: 'Talon Air',
    aircraft: 'Various Business Jet',
    location: 'United States | Farmingdale',
    role: 'Pilot in Command',
    url: 'https://pilotsglobal.com/job/Various-Business-Jet-pilot-in-command-talon_air-US-SpyZt31e0s',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '3500',
    license: 'ATP / ATPL',
    visaSponsorship: 'No',
    picTime: '2000',
    picInTypeTime: '',
    typeRating: 'Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '',
    compensation: 'Very competitive benefits with sign-on bonuses'
  },
  {
    title: 'Line Pilot - PA-31 Navajo',
    company: 'EagleView Technologies',
    aircraft: 'PA-31 Navajo',
    location: 'United States | Home-Based',
    role: 'Line Pilot',
    url: 'https://pilotsglobal.com/job/PA-31-Navajo-line-pilot-eagleview_technologies-US-e0e24edc85',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '400',
    license: 'CPL,ME',
    visaSponsorship: 'No',
    picTime: '',
    picInTypeTime: '',
    typeRating: 'Not Required',
    medicalClass: 'Class 2',
    icaoElpLevel: '',
    compensation: 'Base salary of $31,616 per year + full benefits'
  },
  {
    title: 'Instructor Pilot - Various Business Jet',
    company: 'Northern Jet',
    aircraft: 'Various Business Jet',
    location: 'United States | Orlando',
    role: 'Instructor Pilot',
    url: 'https://pilotsglobal.com/job/Various-Business-Jet-instructor-pilot-northern_jet-US-oB19t9ybr7',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: 'ATP / ATPL',
    visaSponsorship: 'No',
    picTime: '',
    picInTypeTime: '',
    typeRating: 'Not Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '',
    compensation: 'Salary: $25.00 Hourly with comprehensive benefits'
  },
  {
    title: 'Second in Command - Citation Sovereign',
    company: 'Executive Jet Management (EJM)',
    aircraft: 'Citation Sovereign',
    location: 'United States | St. Louis',
    role: 'Second in Command',
    url: 'https://pilotsglobal.com/job/Citation-Sovereign-second-in-command-executive_jet_management_ejm-US-2aP8sxc5vp',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '2500',
    license: 'ATP / ATPL',
    visaSponsorship: 'No',
    picTime: '500',
    picInTypeTime: '',
    typeRating: 'Not Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '',
    compensation: 'Competitive pay with 67% 401(k) match'
  },
  {
    title: 'Pilot in Command - Learjet LR-JET',
    company: 'PlaneSmart Aviation',
    aircraft: 'Learjet LR-JET',
    location: 'United States | Addison',
    role: 'Pilot in Command',
    url: 'https://pilotsglobal.com/job/Learjet-LR-JET-pilot-in-command-planesmart_aviation-US-J1GXtc2k7r',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '2000',
    license: 'ATP / ATPL',
    visaSponsorship: 'No',
    picTime: '1000',
    picInTypeTime: '100',
    typeRating: 'Not Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '',
    compensation: 'Competitive compensation package'
  },
  {
    title: 'Pilot in Command - 208B Grand Caravan Amphibian',
    company: 'Island Air Service',
    aircraft: '208B Grand Caravan Amphibian',
    location: 'United States | Kodiak',
    role: 'Pilot in Command',
    url: 'https://pilotsglobal.com/job/208B-Grand-Caravan-Amphibian-pilot-in-command-island_air_service-US-e788ac3c60',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '1500',
    license: 'CPL',
    visaSponsorship: 'No',
    picTime: '',
    picInTypeTime: '',
    typeRating: 'Not Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '',
    compensation: 'Competitive pay with housing provided'
  },
  {
    title: 'Captain - Citation M2/CJ series',
    company: 'FlyUSA',
    aircraft: 'Citation M2/CJ series',
    location: 'United States | Tampa',
    role: 'Captain',
    url: 'https://pilotsglobal.com/job/Citation-M2-CJ-series-captain-flyusa-US-iAtjshgrpl',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '3000',
    license: 'ATP / ATPL',
    visaSponsorship: 'No',
    picTime: '2000',
    picInTypeTime: '200',
    typeRating: 'Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '',
    compensation: 'Comprehensive benefits with 401(k) match'
  },
  {
    title: 'Pilot in Command - Citation M2/CJ series',
    company: 'Eagle Air Aviation',
    aircraft: 'Citation M2/CJ series',
    location: 'United States | Harrisburg',
    role: 'Pilot in Command',
    url: 'https://pilotsglobal.com/job/Citation-M2-CJ-series-pilot-in-command-eagle_air_aviation-US-TGbgt18qxi',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '3000',
    license: 'ATP / ATPL',
    visaSponsorship: 'No',
    picTime: '1500',
    picInTypeTime: '',
    typeRating: 'Not Required',
    medicalClass: 'Class 1',
    icaoElpLevel: '',
    compensation: 'Competitive salary with sign-on bonus'
  },
  // Original PilotCareerCenter jobs - restored
  {
    title: 'First Officer --- Pilatus PC24 - Campbell River BC',
    company: 'Avalo Air Inc.',
    aircraft: 'Pilatus PC24',
    location: 'Campbell River BC',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23470/Canada/F-O/PC24---CYBL/Avalo-Air-Inc.?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: 'Accepting Apps',
    applicationUrl: 'suzi.gaskill@veyronproperties.com',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Type Rated First Officer --- Cessna CJ - Stuttgart DE',
    company: 'E-Aviation',
    aircraft: 'Cessna CJ',
    location: 'Stuttgart - DE',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23469/Europe-UK/TR-F-O/Cessna-CJ---EDDS/E-Aviation?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: 'https://pilotcareercenter.com/redirect/job/application/click/23469',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Type Rated Captain --- Challenger 350 - Europe',
    company: 'Avcon Jet AG',
    aircraft: 'Challenger 350',
    location: 'Europe',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23468/Europe-UK/TR-CAPT/CL350---Europe/Avcon-Jet?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: 'https://pilotcareercenter.com/redirect/job/careers/click/23468',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'First Officers --- Dash 8 Q400 - Bolzano - IT',
    company: 'SkyAlps',
    aircraft: 'Dash 8',
    location: 'Bolzano - IT',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23467/Europe-UK/F-O%27s/Q400---Bolzano/SkyAlps?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: 'https://pilotcareercenter.com/redirect/job/application/click/23467',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captain --- Dash 8 Q400 - Bolzano - IT',
    company: 'SkyAlps',
    aircraft: 'Dash 8',
    location: 'Bolzano - IT',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23466/Europe-UK/CAPT/Q400---Bolzano/SkyAlps?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: 'https://pilotcareercenter.com/redirect/job/application/click/23466',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captain --- ERJ145 Regional Jet - Zurich',
    company: 'Travelcoup Schweiz AG',
    aircraft: 'ERJ145',
    location: 'Zurich',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23465/Europe-UK/CAPT/ERJ145---Zurich/Travelcoup-Schweiz?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: 'Accepting Apps',
    applicationUrl: 'hr@travelcoup.com',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captain --- Legacy 600 - Europe',
    company: 'Air X Charter Ltd.',
    aircraft: 'Legacy 600',
    location: 'Europe',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23463/Europe-UK/CAPT/Legacy-600---Europe/Air-X?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: 'https://pilotcareercenter.com/redirect/job/application/click/23463',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'First Officer --- Airbus A340 - Europe',
    company: 'Air X Charter Ltd.',
    aircraft: 'Airbus A330',
    location: 'Europe',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23464/Europe-UK/F-O/A340---Europe/Air-X?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: 'https://pilotcareercenter.com/redirect/job/application/click/23464',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Copiloto --- Boeing 737 - Sao Paulo',
    company: 'GOL Linhas Aéreas Inteligentes',
    aircraft: 'Boeing 737',
    location: 'Sao Paulo',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23446/Latin-America-%E2%88%95-the-Caribbean/Copiloto/Boeing-737---GRU/GOL?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: 'https://pilotcareercenter.com/redirect/job/application/click/23446',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'First Officer --- Phenom 300 - Calgary',
    company: 'Flightpath',
    aircraft: 'Phenom 300',
    location: 'Calgary',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/18748/Canada/F-O/Phenom-300---Calgary/Flightpath?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: 'r.hughes@flightpath.ca',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captain --- Phenom 300 - Calgary',
    company: 'Flightpath',
    aircraft: 'Phenom 300',
    location: 'Calgary',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23458/Canada/CAPT/Phenom-300---Calgary/Flightpath?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: 'r.hughes@flightpath.ca',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captain --- Global XRS - Home Based',
    company: 'Flightpath',
    aircraft: 'Global XRS',
    location: 'Home Based',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23459/Canada/CAPT/Global-XRS---Home-Based/Flightpath?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Flight Instructors --- DA20/DA40, PA34 - Trinidad',
    company: 'Aerial World Services',
    aircraft: 'DA20,DA40,PA34',
    location: 'Trinidad',
    role: '',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23457/Latin-America-%E2%88%95-the-Caribbean/Flight-Instr/DA20-40%2C-PA34/Aerial-World?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: 'Accepting Apps',
    applicationUrl: 'aerialservicesltd@gmail.com',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Type Rated First Officer --- Pilatus PC24 - Geneva',
    company: 'Global Jet',
    aircraft: 'Pilatus PC24',
    location: 'Geneva',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23455/Europe-UK/TR-F-O/PC24---Geneva/Global-Jet?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: 'https://pilotcareercenter.com/redirect/job/application/click/23455',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captain --- Beech 1900D - Calgary',
    company: 'Sunwest Aviation',
    aircraft: 'Beech 1900D',
    location: 'Calgary',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/22225/Canada/CAPT/BE02---Calgary/Sunwest?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captain --- LearJet 45 - Calgary',
    company: 'Sunwest Aviation',
    aircraft: 'LearJet 45',
    location: 'Calgary',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/17771/Canada/CAPT/LR45---Calgary/Sunwest?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captain --- King Air 200/350 - Calgary',
    company: 'Sunwest Aviation',
    aircraft: 'King Air 200/350',
    location: 'Calgary',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/22447/Canada/CAPT/King-Air-200-350---YYC/Sunwest?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Type Rated First Officers --- Airbus A320 - London Heathrow',
    company: 'British Airways',
    aircraft: 'Airbus A320',
    location: 'London Heathrow',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23454/Europe-UK/TR-F-O%27s/A320---Heathrow/BA?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Direct Entry Pilot --- Long Haul Fleets - LDN',
    company: 'British Airways',
    aircraft: '',
    location: 'London',
    role: '',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/20008/Europe-UK/Direct-Entry-Pilot/Long-haul---LDN/BA?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captain(s) --- DHC3T - Fishing Lodge',
    company: 'Wings Over Kississing',
    aircraft: 'DHC3T',
    location: 'Fishing Lodge',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23407/Canada/CAPT/DHC3T---Fishing-Lodge/Wings-Over-Kississing?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Special Mission MET Captains --- King Air 350 - Prestwick',
    company: '2Excel Aviation',
    aircraft: 'King Air 350',
    location: 'Prestwick',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23453/Europe-UK/MET-CAPT/BE350---Prestwick/2Excel?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Multi-Engine Turbine F/O --- King Air 350 - Prestwick',
    company: '2Excel Aviation',
    aircraft: 'King Air 350',
    location: 'Prestwick',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/21521/Europe-UK/MET-F-O/BE350---Prestwick/2Excel?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Line Training Captains --- P68 Partenavia - Liverpool UK',
    company: 'Ravenair',
    aircraft: 'P68 Partenavia',
    location: 'Liverpool UK',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23451/Europe-UK/LTC-CAPT/P68---Liverpool/Ravenair?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'P1 Captains --- P68 Partenavia - Liverpool UK',
    company: 'Ravenair',
    aircraft: 'P68 Partenavia',
    location: 'Liverpool UK',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23439/Europe-UK/P1-CAPT/P68---Liverpool/Ravenair?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'P2 Pilots --- P68 Partenavia - Liverpool UK',
    company: 'Ravenair',
    aircraft: 'P68 Partenavia',
    location: 'Liverpool UK',
    role: '',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23452/Europe-UK/P2-Pilots/P68---Liverpool/Ravenair?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Type Rated Captains --- Boeing 737NG - Bucharest',
    company: 'Hello Jets',
    aircraft: 'Boeing 737',
    location: 'Bucharest',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23020/Europe-UK/TR-CAPT/B737NG---Bucharest/Hello-Jets?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Type Rated First Officer --- Boeing 737 - Stockholm',
    company: 'TUIfly Nordic AB',
    aircraft: 'Boeing 737',
    location: 'Stockholm',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23450/Europe-UK/TR-F-O/B737---Stockholm/TUI-Nordic?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Non Rated First Officers --- Embraer E190 - London City UK',
    company: 'BA CityFlyer Limited',
    aircraft: 'Embraer E190',
    location: 'London City UK',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23056/Europe-UK/NTR-F-O%27s/E190---London/BA-CityFlyer?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captain --- Gulfstream G650 - UK/Europe',
    company: 'Flexjet Europe',
    aircraft: 'Gulfstream G650',
    location: 'UK/Europe',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23447/Europe-UK/CAPT/G650---UK-Europe/Flexjet-Europe?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captain --- Global XRS - Bologna IT',
    company: 'Flexjet/Sirio Europe',
    aircraft: 'Global XRS',
    location: 'Bologna IT',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23448/Europe-UK/CAPT/BD700---Bologna/Flexjet-Sirio-Europe?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'First Officer --- Global XRS - Bologna IT',
    company: 'Flexjet/Sirio Europe',
    aircraft: 'Global XRS',
    location: 'Bologna IT',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23449/Europe-UK/F-O/BD700---Bologna/Flexjet-Sirio-Europe?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'NTR TR Captains --- Airbus A320 - Munich, Frankfurt',
    company: 'Lufthansa City Airlines',
    aircraft: 'Airbus A320',
    location: 'Munich, Frankfurt',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/22760/Europe-UK/NTR-TR-CAPT/A320---MUN-FRA/LH-City?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'From Ready to Captain --- Airbus A320 - Munich, Frankfurt',
    company: 'Lufthansa City Airlines',
    aircraft: 'Airbus A320',
    location: 'Munich, Frankfurt',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/19741/Europe-UK/FAST-TRK-CAPT/A320---MUN-FRA/LH-City?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Non Rated First Officer --- Challenger 604/605 - Europe',
    company: 'Air X Charter Ltd.',
    aircraft: 'Challenger 604/605',
    location: 'Europe',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23256/Europe-UK/NTR-F-O/CL604-605---Europe/Air-X?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Type Rated First Officers --- Legacy 650 Jet - Europe',
    company: 'Air X Charter Ltd.',
    aircraft: 'Legacy 650 Jet',
    location: 'Europe',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/21560/Europe-UK/TR-F-O%27s/Legacy-650---EUR/Air-X?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Type Rated First Officers --- Boeing 737 - UK Bases',
    company: 'TUI Airways UK',
    aircraft: 'Boeing 737',
    location: 'UK Bases',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/21934/Europe-UK/TR-F-O%27s-/B737---UK-Bases/TUI-UK?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Non Rated First Officers --- Boeing 737 - UK bases',
    company: 'TUI Airways UK',
    aircraft: 'Boeing 737',
    location: 'UK bases',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/19027/Europe-UK/NTR-F-O%27s/B737---UK/TUI-UK?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Capitán --- Airbus A320 - Medellín',
    company: 'JetSmart',
    aircraft: 'Airbus A320',
    location: 'Medellín',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23445/Latin-America-%E2%88%95-the-Caribbean/Capit%C3%A1n-/Airbus-A320---Medell%C3%ADn-/JetSmart?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Primeros Oficiales --- Airbus A320 - Buenos Aires',
    company: 'JetSmart',
    aircraft: 'Airbus A320',
    location: 'Buenos Aires',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23321/Latin-America-%E2%88%95-the-Caribbean/P-O%27s/A320---Buenos-Aires/JetSmart?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captains --- DHC6-300 Twin Otter Seaplane - USVI',
    company: 'Seaborne Airlines',
    aircraft: 'DHC6 300/400',
    location: 'USVI',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23444/USA/PIC/DHC6-300F---USVI/Seaborne-Airlines?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'CFI --- C172 / PA28',
    company: 'Perfect Approach Aviation',
    aircraft: 'C172,PA28',
    location: '',
    role: '',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23438/Canada/CFI/C172---PA28/Perfect-Approach?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Ground School Instructor --- Heli / Fixed Wing - Abbotsford',
    company: 'Chinook Helicopters/Fixed Wing Training',
    aircraft: '',
    location: 'Abbotsford',
    role: '',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23437/Canada/Ground-School-Instr/Heli-Fixed-Wing---YXX/Chinook-Heli?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captain --- Falcon 2000 EASY - Mississauga',
    company: 'Skyservice Business Aviation',
    aircraft: 'Falcon 2000 EASY',
    location: 'Mississauga',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23443/Canada/CAPT/DA-2000EASY---YYZ/Skyservice?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'First Officer --- Embraer Praetor 600 - Montreal',
    company: 'Skyservice Business Aviation',
    aircraft: 'Embraer Praetor 600',
    location: 'Montreal',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23189/Canada/F-O/Praetor-600-Jet---YUL/Skyservice?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'First Officer --- Learjet 45 - Montreal',
    company: 'Starlink Aviation',
    aircraft: 'Learjet 45',
    location: 'Montreal',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/17657/Canada/F-O/Learjet-45R/Starlink?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captain --- Global 6000 Jet - Montreal',
    company: 'Starlink Aviation',
    aircraft: 'Global 8000',
    location: 'Montreal',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23442/Canada/CAPT/Global-6000---Montreal/Starlink?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captain --- Falcon 2000LX - Montreal (604-OPS)',
    company: 'Starlink Aviation',
    aircraft: 'Falcon 2000LX',
    location: 'Montreal',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23441/Canada/CAPT/Falcon-2000LX---Montreal/Starlink?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'SFI Sim Instructor --- BD700 Global Series - Dubai',
    company: 'CAE Training Center',
    aircraft: 'BD700 Global Series',
    location: 'Dubai',
    role: '',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23440/MENA/Sim-Instructor/BD700-Global---Dubai/CAE-Dubai?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Full Time Instructor Pilot --- Challenger Jets - Montreal',
    company: 'CAE Training Centre',
    aircraft: 'Challenger Jets',
    location: 'Montreal',
    role: '',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23433/Canada/Instructor-Pilot/Challenger-Jets---YUL/CAE-Montreal?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Full Time Instructor Pilot --- Bombardier Global - Montreal',
    company: 'CAE Training Centre',
    aircraft: 'Bombardier Global',
    location: 'Montreal',
    role: '',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23434/Canada/Instructor-Pilot/BD700-Global---YUL/CAE-Montreal?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Charter Pilot --- Cessna 208 Amphib - Toronto',
    company: 'Cameron Air',
    aircraft: 'C208 Caravan Amphibians',
    location: 'Toronto',
    role: '',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23436/Canada/Pilot/C208-Amphib---CYTZ/Cameron-Air?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Non Rated First Officers --- Airbus A320 - Macau',
    company: 'Air Macau',
    aircraft: 'Airbus A320',
    location: 'Macau',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/20800/Asia/NTR-F-O%27s/A320---Macau/Air-Macau?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Type Rated First Officers --- Airbus A320 - Macau',
    company: 'Air Macau',
    aircraft: 'Airbus A320',
    location: 'Macau',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/20799/Asia/TR-F-O%27s/A320---Macau/Air-Macau?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Type Rated Captains --- Airbus A320 - Macau',
    company: 'Air Macau',
    aircraft: 'Airbus A320',
    location: 'Macau',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/20798/Asia/TR-CAPT/A320---Macau/Air-Macau?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'First Officers (Direct Entry) --- A330 A350 B777 B747 - HKG',
    company: 'Cathay Pacific',
    aircraft: 'Airbus A330,Airbus A350,Boeing 777,Boeing 747',
    location: 'HKG',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/12015/Asia/DE-F-O%27s/A330-A350-B777-B747/Cathay?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'PIC --- Caravan C208B - Trinidad',
    company: 'Kingfisher Air Services',
    aircraft: 'C208 Caravan Amphibians',
    location: 'Trinidad',
    role: '',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23435/Latin-America-%E2%88%95-the-Caribbean/PIC/C208B---Trinidad/Kingfisher-Air?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captains --- Dash 8 - Montreal',
    company: 'Central Mountain Air',
    aircraft: 'Dash 8',
    location: 'Montreal',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23016/Canada/CAPT/Dash-8---Montreal/CMA?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Seaplane Pilot --- DHC2 Beaver - Prince Rupert',
    company: 'Inland Air Charters',
    aircraft: 'DHC2 Beaver',
    location: 'Prince Rupert',
    role: 'Seaplane Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23432/Canada/Float-Pilot/DHC2---Seal-Cove/Inland-Air?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Type Rated Captain --- Falcon 7X - Lugano CH',
    company: 'Albinati Aeronautics',
    aircraft: 'Falcon 7X',
    location: 'Lugano CH',
    role: 'Captain',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/23431/Europe-UK/TR-CAPT/Falcon-7X---Lugano/Albinati-Aero?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Type Rated First Officer --- Falcon 8X - Europe/Africa',
    company: 'Elit\'Avia International',
    aircraft: 'Falcon 8X',
    location: 'Europe/Africa',
    role: 'First Officer',
    url: 'https://pilotcareercenter.com/Pilot-Job-Posting-Pilot-Opening-Pilot-Job/22307/Europe-UK/TR-F-O/DA8X---EUR-AFR/Elit%27Avia-Intnl?NextJobMode=GlobalHomepage',
    posted: '2025-03-19',
    status: '',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  // LatestPilotJobs.com - 133 new jobs to expand database
  {
    title: 'Phenom 300E (EMB505) Captain Based at Zürich / 8 ON / 6 OFF',
    company: 'Haute Aviation',
    aircraft: 'Embraer Phenom 300/300E',
    location: 'Switzerland',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19700.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'A320 First Officer Experience or Employment for Low Time Non-Type Rated EASA Pilots',
    company: 'Eagle Jet International, Inc.',
    aircraft: 'Airbus 320',
    location: 'Europe',
    role: 'First Officer',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/18174.html',
    posted: '2025-03-12',
    status: 'Accepting Apps',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Upgrade to B777 PIC',
    company: 'Root Aviation',
    aircraft: 'Boeing 777',
    location: 'Asia',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19683.html',
    posted: '2025-03-17',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captain (m/f/d)',
    company: 'SkyAlps',
    aircraft: 'All Pilot',
    location: 'Italy',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/18908.html',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'First Officer (m/f/d)',
    company: 'SkyAlps',
    aircraft: 'All Pilot',
    location: 'Italy',
    role: 'First Officer',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/17300.html',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Experienced A320/B737 Pilots -- Online Open Day',
    company: 'Getjet Airlines',
    aircraft: 'Airbus 320, Boeing 737 - 6/7/8/900 NG',
    location: 'Lithuania',
    role: 'All Pilot',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19479.html',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'DHC8 TRI/SFI Instructors',
    company: 'BAA Training',
    aircraft: 'DHC - 8 Dash 8',
    location: 'Spain',
    role: 'Type Rating Instructor (TRI)',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/17486.html',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'First Officer G7500 - Open Base',
    company: 'Globaljet',
    aircraft: 'Global 7500',
    location: 'Europe',
    role: 'First Officer',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/17737.html',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Second-In Command CL30 -- Challenger 300',
    company: 'Gary Jet Center',
    aircraft: 'Challenger 300',
    location: 'INDIANA',
    role: 'First Officer',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/17155.html',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Theoretical Knowledge Instructor M/F',
    company: 'Astonfly',
    aircraft: 'All Pilot',
    location: 'France',
    role: 'Flight/Ground Instructor',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/15971.html',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Flight Instructor H/F',
    company: 'Astonfly',
    aircraft: 'All Pilot',
    location: 'France',
    role: 'Flight/Ground Instructor',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/15784.html',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'First Officer A320 (m/w/d)',
    company: 'K5 Aviation',
    aircraft: 'Airbus 320',
    location: 'Germany',
    role: 'First Officer',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/16182.html',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'B757/B767 to B777 Captains',
    company: 'Root Aviation',
    aircraft: 'Boeing 757, Boeing 767, Boeing 777',
    location: 'Asia',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19692.html',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captain Citation C525 *NEW TERMS INCLUDING SIGN ON BONUS OF 10.000€ AND UPDATED SALARY PACKAGE*',
    company: 'Excellent Air GmbH',
    aircraft: 'Citation 525A CJ1/CJ2',
    location: 'Europe',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/18981.html',
    posted: '2025-03-16',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'B747 to B777 PIC',
    company: 'Root Aviation',
    aircraft: 'Boeing 747 - 400, Boeing 777',
    location: 'Asia',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19691.html',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Upgrade to B777 PIC',
    company: 'Root Aviation',
    aircraft: 'Boeing 777',
    location: 'Asia',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19690.html',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Chief Flight Instructor',
    company: 'SKIES AVIATION ACADEMY',
    aircraft: 'All Pilot',
    location: 'Greece',
    role: 'Flight/Ground Instructor',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/18989.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Flight Instructor',
    company: 'SKIES AVIATION ACADEMY',
    aircraft: 'All Pilot',
    location: 'Europe',
    role: 'Flight/Ground Instructor',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19686.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Upgrade to B777 PIC',
    company: 'Root Aviation Ltd',
    aircraft: 'Boeing 747 - 400, Boeing 757, Boeing 767, Boeing 777',
    location: 'Asia',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19581.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'B757/B767 to B777 Captains',
    company: 'Root Aviation Ltd',
    aircraft: 'Boeing 747 - 400, Boeing 757, Boeing 767, Boeing 777',
    location: 'Asia',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19647.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'A320 Captains (EASA/ICAO)',
    company: 'WingJet Aviation',
    aircraft: 'Airbus 320',
    location: 'Europe',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19674.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Class Rating Instructor (DA42 Greece)',
    company: '(MEMBERS ONLY)',
    aircraft: 'Diamond DA42',
    location: 'Greece',
    role: 'Flight/Ground Instructor',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19687.html',
    posted: '2025-03-18',
    status: 'Accepting Apps',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'CAPTAIN FOR CHALLENGER 601/604',
    company: '(MEMBERS ONLY)',
    aircraft: 'Challenger 600/601, Challenger 604/605',
    location: 'All Pilot',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19344.html',
    posted: '2025-03-18',
    status: 'Accepting Apps',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Direct Entry Captain A320 in London',
    company: 'Scandinavian Airlines',
    aircraft: 'Airbus 320',
    location: 'United Kingdom',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/18168.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'First Officer - Lineage 1000 (EMB170/190)',
    company: 'AirX Charter Ltd',
    aircraft: 'Embraer E-170/190',
    location: 'Europe',
    role: 'First Officer',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19489.html',
    posted: '2025-03-12',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captains & First Officers - Various types',
    company: 'AeroProfessional Ltd',
    aircraft: 'All Airbus 220',
    location: 'Angola',
    role: 'Captain, First Officer',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19696.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Typed/Current Hawker 800XP PIC',
    company: 'Jet Access',
    aircraft: 'Hawker 800XP',
    location: 'FLORIDA',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19328.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'First Officer PC24 - Geneva Area',
    company: 'Globaljet',
    aircraft: 'Pilatus PC24',
    location: 'Europe',
    role: 'First Officer',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/17008.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'First Officer - CRJ-200',
    company: 'Air Wisconsin',
    aircraft: 'CRJ 200/900',
    location: 'WISCONSIN',
    role: 'First Officer',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/17414.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captain / Commander A320 - 100%',
    company: 'Chair Airlines',
    aircraft: 'Airbus 320',
    location: 'Switzerland',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/17483.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'BA Cityflyer Direct Entry Captain',
    company: 'BA Cityflyer',
    aircraft: 'All Pilot',
    location: 'United Kingdom',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/17697.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captain Falcon 7X - Oxford, Connecticut',
    company: 'Jet Aviation',
    aircraft: 'Falcon 7X',
    location: 'CONNECTICUT',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/17103.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Captain PC-24 - Cannes',
    company: 'Fly 7',
    aircraft: 'Pilatus PC24',
    location: 'France',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/16484.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'First Officer PC-24 - Cannes',
    company: 'Fly 7',
    aircraft: 'Pilatus PC24',
    location: 'France',
    role: 'First Officer',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/17130.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'B747/757/767 to B777 PIC',
    company: 'Root Aviation',
    aircraft: 'Boeing 747 - 400, Boeing 757, Boeing 767, Boeing 777',
    location: 'Asia',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19698.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Global Express XRS Captain Home Base: Payerne, Switzerland (LSMP)',
    company: 'Haute Aviation',
    aircraft: 'Global Express',
    location: 'Switzerland',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19699.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'B777 PIC with China Southern',
    company: 'Root Aviation',
    aircraft: 'Boeing 777',
    location: 'Asia',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19697.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Skyflyers Aviation is Hiring A320 Captains (EASA /ICAO Holders)!',
    company: 'SKYFLYERS AVIATION',
    aircraft: 'Airbus 320',
    location: 'Europe',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19673.html',
    posted: '2025-03-17',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'A320 Captain (type-rated)',
    company: '(MEMBERS ONLY)',
    aircraft: 'Airbus 320',
    location: 'All Pilot',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19428.html',
    posted: '2025-03-17',
    status: 'Accepting Apps',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'EMB190 E1 EASA Type Rated First Officers',
    company: '(MEMBERS ONLY)',
    aircraft: 'Embraer E-170/190',
    location: 'All Pilot',
    role: 'First Officer',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19682.html',
    posted: '2025-03-17',
    status: 'Accepting Apps',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'EMB190 E1 EASA Type Rated Captains',
    company: '(MEMBERS ONLY)',
    aircraft: 'Embraer E-170/190',
    location: 'All Pilot',
    role: 'Captain',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19681.html',
    posted: '2025-03-17',
    status: 'Accepting Apps',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Pilot - Lear 60 SIC',
    company: 'FlightWorks',
    aircraft: 'Learjet 60',
    location: 'GEORGIA',
    role: 'First Officer',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/18486.html',
    posted: '2025-03-17',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'First Officer (m/f/d)',
    company: 'K5-Aviation',
    aircraft: 'All Pilot',
    location: 'Germany',
    role: 'First Officer',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/18182.html',
    posted: '2025-03-17',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Pilatus PC-24 Second-in-Command (SIC)',
    company: 'flyADVANCED',
    aircraft: 'Pilatus PC24',
    location: 'DELAWARE',
    role: 'First Officer',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/17085.html',
    posted: '2025-03-17',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'ICAO PIC/SIC CL850 24 - 26 March',
    company: '(MEMBERS ONLY)',
    aircraft: 'Challenger 850',
    location: 'All Pilot',
    role: 'Captain, First Officer',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19695.html',
    posted: '2025-03-17',
    status: 'Accepting Apps',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Wizz Air UK is looking for First Officers and Captains',
    company: 'Wizz Air UK',
    aircraft: 'All Pilot',
    location: 'United Kingdom',
    role: 'Captain, First Officer',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/19685.html',
    posted: '2025-03-17',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'B1 Licensed Engineer - Glasgow',
    company: 'Jet2.com',
    aircraft: '',
    location: 'United Kingdom',
    role: 'Other',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/18175.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Fleet Airworthiness Engineer (CAMO)',
    company: 'Volotea',
    aircraft: '',
    location: 'Spain',
    role: 'Other',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/18483.html',
    posted: '2025-03-18',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  },
  {
    title: 'Senior Flight Dispatcher',
    company: 'Pegasus Airlines',
    aircraft: 'No Type Rating',
    location: 'Turkey',
    role: 'Other',
    url: 'https://www.latestpilotjobs.com/jobs/view/id/17496.html',
    posted: '2025-03-19',
    status: 'Hiring Now!',
    applicationUrl: '',
    flightTime: '',
    license: '',
    visaSponsorship: '',
    picTime: '',
    picInTypeTime: '',
    typeRating: '',
    medicalClass: '',
    icaoElpLevel: '',
    compensation: ''
  }
];

const PilotJobDatabasePage: React.FC = () => {
  const [selectedAircraft, setSelectedAircraft] = useState<string>('all');
  const [selectedLocation, setSelectedLocation] = useState<string>('all');
  const [selectedRole, setSelectedRole] = useState<string>('all');
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [activeCategory, setActiveCategory] = useState<string>('all');

  const aircraftTypes = Array.from(new Set(jobApplicationListings.map(job => job.aircraft)));
  const locations = Array.from(new Set(jobApplicationListings.map(job => job.location)));
  const roles = Array.from(new Set(jobApplicationListings.map(job => job.role)));

  const parseHours = (value?: string | number) => {
    if (value === undefined || value === null) return null;
    if (typeof value === 'number') return value;
    const numeric = value.replace(/[^0-9.]/g, '');
    return numeric ? parseInt(numeric, 10) : null;
  };

  const categoryFilters = [
    { id: 'all', label: 'All Jobs' },
    { id: 'low-timer', label: 'Low Timer' },
    { id: 'mid-timer', label: 'Mid Timer' },
    { id: 'high-timer', label: 'High Timer' },
    { id: 'corporate', label: 'Corporate' },
    { id: 'airline', label: 'Airline' },
    { id: 'captain', label: 'Captain' },
    { id: 'first-officer', label: 'First Officer' },
    { id: 'second-officer', label: 'Second Officer' },
    { id: 'cadet-program', label: 'Cadet Program' }
  ];

  const jobMatchesCategory = (job: typeof jobApplicationListings[number], category: string) => {
    if (category === 'all') return true;
    const role = (job.role || '').toLowerCase();
    const title = job.title.toLowerCase();
    const company = (job.company || '').toLowerCase();
    const flightHours = parseHours(job.flightTime || job.picTime);

    switch (category) {
      case 'low-timer': {
        if (flightHours !== null && flightHours < 1000) return true;
        return role.includes('cadet') || role.includes('second in command') || title.includes('cadet');
      }
      case 'mid-timer':
        return flightHours !== null && flightHours >= 1000 && flightHours < 4000;
      case 'high-timer':
        return flightHours !== null && flightHours >= 4000;
      case 'corporate':
        return role.includes('corporate') || title.includes('corporate') || title.includes('pilot in command') || company.includes('jet') || company.includes('aviation');
      case 'airline':
        return company.includes('air') || company.includes('airline');
      case 'captain':
        return role.includes('captain');
      case 'first-officer':
        return role.includes('first officer');
      case 'second-officer':
        return role.includes('second') || role.includes('sic');
      case 'cadet-program':
        return role.includes('cadet') || title.includes('cadet');
      default:
        return true;
    }
  };

  const totalJobs = jobApplicationListings.length;
  const uniqueAirlines = new Set(jobApplicationListings.map(job => job.company)).size;
  const uniqueAircraft = new Set(jobApplicationListings.map(job => job.aircraft)).size;

  const filteredListings = jobApplicationListings.filter(job => {
    const matchesAircraft = selectedAircraft === 'all' || job.aircraft === selectedAircraft;
    const matchesLocation = selectedLocation === 'all' || job.location.includes(selectedLocation);
    const matchesRole = selectedRole === 'all' || job.role === selectedRole;
    const query = searchQuery.trim().toLowerCase();
    const matchesSearch =
      query.length === 0 ||
      [job.title, job.company, job.aircraft, job.location, job.role, job.status]
        .filter(Boolean)
        .some(field => field!.toLowerCase().includes(query));
    const matchesCategory = jobMatchesCategory(job, activeCategory);

    return matchesAircraft && matchesLocation && matchesRole && matchesSearch && matchesCategory;
  });

  return (
    <div className="dashboard-container animate-fade-in" style={{ alignItems: 'stretch', justifyContent: 'center', padding: '3rem 2rem 4rem', minHeight: '100vh', background: 'radial-gradient(circle at top, #e0f2ff 0%, #f8fbff 45%, #f1f5f9 100%)' }}>
      <main className="dashboard-card" style={{ width: '100%', maxWidth: '1440px', padding: '0', background: 'transparent', boxShadow: 'none' }}>
        <header style={{ marginBottom: '2.5rem', borderRadius: '24px', background: 'linear-gradient(120deg, #0f172a, #1d4ed8)', color: 'white', padding: '2.5rem', boxShadow: '0 25px 60px rgba(15, 23, 42, 0.35)' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '1rem' }}>
            <a
              href="/"
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: '0.5rem',
                padding: '0.5rem 1rem',
                background: 'rgba(14, 165, 233, 0.1)',
                color: '#0ea5e9',
                borderRadius: '999px',
                textDecoration: 'none',
                fontSize: '0.9rem',
                fontWeight: 500,
                transition: 'all 0.2s ease'
              }}
            >
              <Icons.ArrowLeft style={{ width: 16, height: 16 }} />
              Back to Home
            </a>
          </div>
          <h1 style={{ fontSize: '2.8rem', fontWeight: 500, marginBottom: '0.5rem', fontFamily: '"Georgia", serif' }}>
            Pilot Job Application Atlas
          </h1>
          <p style={{ color: 'rgba(226, 232, 240, 0.85)', fontSize: '1rem', lineHeight: 1.7, maxWidth: '840px' }}>
            Explore every active cockpit opportunity in a single view. Use precision search + curated categories to jump between cadet programs, corporate flight decks, or high-timer airline commands in seconds.
          </p>

          <div style={{ marginTop: '2rem', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '1rem' }}>
            {[
              { label: 'Live Roles', value: totalJobs },
              { label: 'Airlines & Operators', value: uniqueAirlines },
              { label: 'Aircraft Types', value: uniqueAircraft }
            ].map(stat => (
              <div key={stat.label} style={{ background: 'rgba(15, 23, 42, 0.25)', borderRadius: '18px', padding: '1rem 1.25rem', border: '1px solid rgba(255,255,255,0.15)' }}>
                <div style={{ textTransform: 'uppercase', fontSize: '0.75rem', letterSpacing: '0.15em', color: 'rgba(248, 250, 252, 0.7)' }}>{stat.label}</div>
                <div style={{ fontSize: '1.8rem', fontWeight: 600 }}>{stat.value}</div>
              </div>
            ))}
          </div>
        </header>

        <section style={{ background: 'white', borderRadius: '28px', padding: '2.25rem', boxShadow: '0 20px 45px rgba(15, 23, 42, 0.12)', marginBottom: '2.5rem' }}>
        <div style={{ marginBottom: '1.5rem' }}>
          <label style={{ display: 'block', fontSize: '0.85rem', color: '#0f172a', fontWeight: 600, marginBottom: '0.5rem' }}>Search jobs</label>
          <div style={{ position: 'relative' }}>
            <Icons.Search style={{ position: 'absolute', left: '0.75rem', top: '50%', transform: 'translateY(-50%)', color: '#94a3b8', width: 18, height: 18 }} />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search by title, airline, aircraft, or location"
              style={{
                width: '100%',
                padding: '0.65rem 0.75rem 0.65rem 2.5rem',
                border: '1px solid #e2e8f0',
                borderRadius: '999px',
                fontSize: '0.95rem',
                color: '#0f172a',
                background: 'white',
                boxShadow: '0 1px 3px rgba(15, 23, 42, 0.08)'
              }}
            />
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '1.25rem', marginBottom: '2rem' }}>
          <div>
            <label style={{ display: 'block', fontSize: '0.85rem', color: '#0f172a', fontWeight: 600, marginBottom: '0.5rem' }}>
              Aircraft Type
            </label>
            <select
              value={selectedAircraft}
              onChange={(e) => setSelectedAircraft(e.target.value)}
              style={{
                width: '100%',
                padding: '0.65rem 0.75rem',
                border: '1px solid #d7dfea',
                borderRadius: '12px',
                fontSize: '0.95rem',
                background: 'white',
                color: '#0f172a'
              }}
            >
              <option value="all">All Aircraft</option>
              {aircraftTypes.map(type => (
                <option key={type} value={type}>{type}</option>
              ))}
            </select>
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '0.85rem', color: '#0f172a', fontWeight: 600, marginBottom: '0.5rem' }}>
              Location
            </label>
            <select
              value={selectedLocation}
              onChange={(e) => setSelectedLocation(e.target.value)}
              style={{
                width: '100%',
                padding: '0.65rem 0.75rem',
                border: '1px solid #d7dfea',
                borderRadius: '12px',
                fontSize: '0.95rem',
                background: 'white',
                color: '#0f172a'
              }}
            >
              <option value="all">All Locations</option>
              {locations.map(loc => (
                <option key={loc} value={loc}>{loc}</option>
              ))}
            </select>
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '0.85rem', color: '#0f172a', fontWeight: 600, marginBottom: '0.5rem' }}>
              Role
            </label>
            <select
              value={selectedRole}
              onChange={(e) => setSelectedRole(e.target.value)}
              style={{
                width: '100%',
                padding: '0.65rem 0.75rem',
                border: '1px solid #d7dfea',
                borderRadius: '12px',
                fontSize: '0.95rem',
                background: 'white',
                color: '#0f172a'
              }}
            >
              <option value="all">All Roles</option>
              {roles.map(role => (
                <option key={role} value={role}>{role}</option>
              ))}
            </select>
          </div>
        </div>

        <div style={{ marginBottom: '1.5rem', display: 'flex', flexWrap: 'wrap', gap: '0.75rem' }}>
          {categoryFilters.map(filter => (
            <button
              key={filter.id}
              onClick={() => setActiveCategory(filter.id)}
              style={{
                border: '1px solid rgba(37, 99, 235, 0.2)',
                padding: '0.55rem 1.25rem',
                borderRadius: '999px',
                fontSize: '0.85rem',
                fontWeight: 600,
                letterSpacing: '0.02em',
                cursor: 'pointer',
                background: activeCategory === filter.id ? 'linear-gradient(120deg, #2563eb, #38bdf8)' : '#f8fafc',
                color: activeCategory === filter.id ? 'white' : '#0f172a',
                boxShadow: activeCategory === filter.id ? '0 12px 25px rgba(37, 99, 235, 0.35)' : 'inset 0 1px 0 rgba(255,255,255,0.9)',
                transition: 'all 0.2s ease'
              }}
            >
              {filter.label}
            </button>
          ))}
        </div>

        <div style={{ padding: '1.75rem 2rem', background: '#0f172a', color: 'white', display: 'flex', flexWrap: 'wrap', gap: '1.25rem', alignItems: 'center', justifyContent: 'space-between', position: 'sticky', top: 0, zIndex: 2 }}>
          <div>
            <div style={{ fontSize: '0.8rem', opacity: 0.8, textTransform: 'uppercase', letterSpacing: '0.2em' }}>Live Listings</div>
            <div style={{ fontSize: '1.5rem', fontWeight: 600 }}>Showing {filteredListings.length} of {totalJobs}</div>
          </div>
          <div style={{ display: 'flex', gap: '1.5rem' }}>
            <div>
              <div style={{ fontSize: '0.75rem', opacity: 0.8 }}>Active Filters</div>
              <div style={{ fontWeight: 600 }}>{activeCategory === 'all' ? 'All Categories' : categoryFilters.find(f => f.id === activeCategory)?.label}</div>
            </div>
            <div>
              <div style={{ fontSize: '0.75rem', opacity: 0.8 }}>Search</div>
              <div style={{ fontWeight: 600 }}>{searchQuery ? `“${searchQuery}”` : 'None'}</div>
            </div>
          </div>
        </div>

        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'separate', borderSpacing: 0, minWidth: '900px' }}>
            <thead>
              <tr style={{ background: '#f8fafc', textTransform: 'uppercase', fontSize: '0.75rem', letterSpacing: '0.08em', color: '#475569', position: 'sticky', top: 104, zIndex: 1 }}>
                {['Job Title', 'Airline', 'Aircraft', 'Location', 'Role', 'Status'].map(heading => (
                  <th key={heading} style={{ textAlign: 'left', padding: '1rem 1.75rem', borderBottom: '1px solid #e2e8f0', background: '#f8fafc' }}>{heading}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {filteredListings.map((job, index) => (
                <tr
                  key={`${job.title}-${index}`}
                  style={{ borderTop: '1px solid #edf2f7', background: 'white' }}
                  onMouseEnter={(e) => (e.currentTarget.style.background = '#f5f7fb')}
                  onMouseLeave={(e) => (e.currentTarget.style.background = 'white')}
                >
                  <td style={{ padding: '1.15rem 1.75rem', fontWeight: 600, color: '#1d4ed8' }}>
                    <a href={job.url} target="_blank" rel="noopener noreferrer" style={{ textDecoration: 'none', color: 'inherit' }}>
                      {job.title}
                    </a>
                    <div style={{ fontSize: '0.8rem', color: '#94a3b8', marginTop: '0.35rem' }}>{job.posted ? `Posted ${job.posted}` : job.company}</div>
                  </td>
                  <td style={{ padding: '1.15rem 1.75rem', fontWeight: 500 }}>{job.company}</td>
                  <td style={{ padding: '1.15rem 1.75rem', color: '#475569' }}>{job.aircraft}</td>
                  <td style={{ padding: '1.15rem 1.75rem', color: '#475569' }}>{job.location}</td>
                  <td style={{ padding: '1.15rem 1.75rem' }}>
                    {job.role && (
                      <span style={{ display: 'inline-flex', alignItems: 'center', padding: '0.3rem 0.85rem', borderRadius: '999px', background: 'rgba(14, 165, 233, 0.12)', color: '#0ea5e9', fontWeight: 600, fontSize: '0.8rem' }}>
                        {job.role}
                      </span>
                    )}
                  </td>
                  <td style={{ padding: '1.15rem 1.75rem' }}>
                    <span style={{ display: 'inline-flex', alignItems: 'center', padding: '0.35rem 0.95rem', borderRadius: '999px', background: job.status === 'Hiring Now!' ? 'rgba(16, 185, 129, 0.15)' : 'rgba(249, 115, 22, 0.15)', color: job.status === 'Hiring Now!' ? '#059669' : '#f97316', fontWeight: 600, fontSize: '0.8rem' }}>
                      {job.status || 'Open'}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {filteredListings.length === 0 && (
          <div style={{ textAlign: 'center', padding: '3rem', color: '#64748b' }}>
            <div style={{ fontSize: '1.1rem', marginBottom: '0.5rem' }}>No jobs found matching your filters</div>
            <div style={{ fontSize: '0.9rem' }}>Try adjusting your filter criteria to see more listings</div>
          </div>
        )}

        <div style={{ marginTop: '2rem', padding: '1.5rem', background: 'rgba(14, 165, 233, 0.05)', borderRadius: '12px', border: '1px solid rgba(14, 165, 233, 0.2)' }}>
          <h3 style={{ fontSize: '1.1rem', color: '#0f172a', marginBottom: '0.75rem', fontFamily: '"Georgia", serif' }}>About This Database</h3>
          <p style={{ color: '#64748b', fontSize: '0.9rem', lineHeight: 1.6, marginBottom: '1rem' }}>
            This job database aggregates pilot opportunities from across the Asia-Pacific region. Listings are sourced from leading aviation career platforms and updated regularly. Each listing includes direct links to original postings for complete details and application instructions.
          </p>
          <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
            <a
              href="/inquiry"
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: '0.5rem',
                padding: '0.75rem 1.5rem',
                background: '#0ea5e9',
                color: 'white',
                borderRadius: '999px',
                textDecoration: 'none',
                fontSize: '0.9rem',
                fontWeight: 500,
                transition: 'all 0.2s ease'
              }}
            >
              Request API Access
            </a>
            <a
              href="https://pilotcareercenter.com/ASIA"
              target="_blank"
              rel="noopener noreferrer"
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: '0.5rem',
                padding: '0.75rem 1.5rem',
                background: 'white',
                color: '#0f172a',
                borderRadius: '999px',
                textDecoration: 'none',
                fontSize: '0.9rem',
                fontWeight: 500,
                border: '1px solid #e2e8f0',
                transition: 'all 0.2s ease'
              }}
            >
              View Source Platform
            </a>
          </div>
        </div>
        </section>
      </main>
    </div>
  );
};

export default PilotJobDatabasePage;
